---
title: 'Class 04: Intro to API'
author: "Sarah Sizemore"
date: "2026-02-11"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    code_download: TRUE
    code_folding: show
    
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Getting Data from the USAJobs API
```{r our_request}
# var request = require('request');    
#             
# var host = 'data.usajobs.gov';  
# var userAgent = 'your@email.address';  
# var authKey = 'YourAPIKey';    
#             
# request({      
#     url: 'https://data.usajobs.gov/api/search?JobCategoryCode=2210&Keyword=Software Development&LocationName=Washington, DC',      
#     method: 'GET',      
#     headers: {          
#         "Host": host,          
#         "User-Agent": userAgent,          
#         "Authorization-Key": authKey      
#     }  
# }, function(error, response, body) {      
#     var data = JSON.parse(body);  
# });



host <- "data.usajobs.gov"
user_agent <- "sizemosd@miamioh.edu"
auth_key <- Sys.getenv("USAJOBS_API_KEY")



my_req =httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_headers(
    # LHS: Name of the Header Input per the API documentation
    # Note that this is case sensitive 
    # I added `back ticks` (key next to 1) for header inputs that had ""
    
    #RHS: is name of object in r which we defined in lines 42-44
    Host = host,          
    `User-Agent` = user_agent,          
    `Authorization-Key`= auth_key
    ) |>
    httr2::req_url_query(
      # JobCategoryCode=2210&Keyword=Software Development
      JobCategoryCode = 2210,
      Keyword = "Data Analyst",
      ResultsPerPage =500)

response =httr2::req_perform(my_req)

usajobs_data = response |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = T)

# By inspecting the usajobs_data (global envioronment -> clicked on the blue circle that has a triangle); Alternativley you could have done

dplyr::glimpse(usajobs_data)

usa_jobs_df = usajobs_data$SearchResult$SearchResultItems

# Q1: Number of Fed Jobs based on our criteria --> 30
usajobs_data$SearchResult$SearchResultCountAll
#also from nrow(usajobs_df)

# Let us clean some of these list columns so you know how that is done


usajobs_df = usajobs_df |>
  tidyr::unnest(
    cols = c(
      "MatchedObjectDescription.PositionLocation",
      "MatchedObjectDescription.JobCategory",
      "MatchedObjectDescription.PositionSchedule"
    ),
    names_sep = '.'
  )

  



```